# Generated by Django 3.2.7 on 2022-11-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20221117_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model_new1',
            name='pic',
            field=models.ImageField(default=' ', upload_to='img_blog'),
        ),
        migrations.AlterField(
            model_name='blog_model_new1',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
