# Generated by Django 3.2.7 on 2022-11-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20221118_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_model_new1',
            old_name='pic',
            new_name='image',
        ),
    ]
